//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doc_obr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doc_obr()
        {
            this.Sotrudnik = new HashSet<Sotrudnik>();
        }
    
        public int id { get; set; }
        public string series { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> issue_date { get; set; }
        public Nullable<int> sotr_id { get; set; }
        public Nullable<int> uch_zav_id { get; set; }
        public Nullable<int> spesh_id { get; set; }
        public Nullable<int> kval_id { get; set; }
        public string description { get; set; }
    
        public virtual Kvalifikaciya Kvalifikaciya { get; set; }
        public virtual Specialnost Specialnost { get; set; }
        public virtual Uchebnoe_zavedenie Uchebnoe_zavedenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sotrudnik> Sotrudnik { get; set; }
    }
}
