//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta_ucheta
    {
        public int id_card { get; set; }
        public string seria { get; set; }
        public string nomer { get; set; }
        public Nullable<int> id_sotrudnika { get; set; }
        public Nullable<int> id_podrazdeleniya { get; set; }
        public Nullable<int> id_dolzhnosti { get; set; }
        public Nullable<int> id_stavki { get; set; }
        public Nullable<System.DateTime> data_priema { get; set; }
        public Nullable<System.DateTime> data_uvolneniya { get; set; }
    
        public virtual Dolzhnosti Dolzhnosti { get; set; }
        public virtual Podrazdelenie Podrazdelenie { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual Stavka Stavka { get; set; }
    }
}
