//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class exEntities : DbContext
    {
        public exEntities()
            : base("name=exEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doc_obr> Doc_obr { get; set; }
        public virtual DbSet<Dolzhnosti> Dolzhnosti { get; set; }
        public virtual DbSet<Karta_ucheta> Karta_ucheta { get; set; }
        public virtual DbSet<Kvalifikaciya> Kvalifikaciya { get; set; }
        public virtual DbSet<Podrazdelenie> Podrazdelenie { get; set; }
        public virtual DbSet<Predpriyatie> Predpriyatie { get; set; }
        public virtual DbSet<Price_kurs> Price_kurs { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<Specialnost> Specialnost { get; set; }
        public virtual DbSet<Stavka> Stavka { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Uchebnoe_zavedenie> Uchebnoe_zavedenie { get; set; }
        public virtual DbSet<Zayavka> Zayavka { get; set; }
    }
}
