//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Podrazdelenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Podrazdelenie()
        {
            this.Karta_ucheta = new HashSet<Karta_ucheta>();
        }
    
        public int id_podrazdeleniya { get; set; }
        public Nullable<int> rukovoditel { get; set; }
        public Nullable<int> kolichestvo_sotrudnikov { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Karta_ucheta> Karta_ucheta { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
