//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public int id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<int> sotr_id { get; set; }
        public Nullable<int> predpriyatie_id { get; set; }
        public Nullable<int> price_kurs_id { get; set; }
    
        public virtual Predpriyatie Predpriyatie { get; set; }
        public virtual Price_kurs Price_kurs { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
